# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_detect(object):
    def setupUi(self, detect):
        detect.setObjectName("detect")
        detect.resize(406, 460)
        self.pushButton = QtWidgets.QPushButton(detect)
        self.pushButton.setGeometry(QtCore.QRect(20, 390, 181, 51))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(detect)
        self.graphicsView.setGeometry(QtCore.QRect(40, 90, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.progressBar = QtWidgets.QProgressBar(detect)
        self.progressBar.setGeometry(QtCore.QRect(40, 300, 261, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.FPS = QtWidgets.QLCDNumber(detect)
        self.FPS.setGeometry(QtCore.QRect(50, 50, 64, 23))
        self.FPS.setDigitCount(5)
        self.FPS.setProperty("value", 100.0)
        self.FPS.setObjectName("FPS")
        self.pushButton_2 = QtWidgets.QPushButton(detect)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 397, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(detect)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 330, 222, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.retranslateUi(detect)
        QtCore.QMetaObject.connectSlotsByName(detect)

    def retranslateUi(self, detect):
        _translate = QtCore.QCoreApplication.translate
        detect.setWindowTitle(_translate("detect", "Dialog"))
        self.pushButton.setText(_translate("detect", "click to start detect"))
        self.pushButton_2.setText(_translate("detect", "STOP"))
        self.commandLinkButton.setText(_translate("detect", "enter command"))
