# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_detect(object):
    def setupUi(self, detect):
        detect.setObjectName("detect")
        detect.resize(793, 878)
        self.pushButton = QtWidgets.QPushButton(detect)
        self.pushButton.setGeometry(QtCore.QRect(20, 770, 181, 51))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(detect)
        self.graphicsView.setGeometry(QtCore.QRect(40, 90, 691, 591))
        self.graphicsView.setObjectName("graphicsView")
        self.progressBar = QtWidgets.QProgressBar(detect)
        self.progressBar.setGeometry(QtCore.QRect(30, 720, 261, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.FPS = QtWidgets.QLCDNumber(detect)
        self.FPS.setGeometry(QtCore.QRect(50, 50, 64, 23))
        self.FPS.setDigitCount(5)
        self.FPS.setProperty("value", 100.0)
        self.FPS.setObjectName("FPS")
        self.pushButton_2 = QtWidgets.QPushButton(detect)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 780, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.timeEdit = QtWidgets.QTimeEdit(detect)
        self.timeEdit.setGeometry(QtCore.QRect(350, 40, 118, 22))
        self.timeEdit.setObjectName("timeEdit")

        self.retranslateUi(detect)
        QtCore.QMetaObject.connectSlotsByName(detect)

    def retranslateUi(self, detect):
        _translate = QtCore.QCoreApplication.translate
        detect.setWindowTitle(_translate("detect", "Dialog"))
        self.pushButton.setText(_translate("detect", "click to start detect"))
        self.pushButton_2.setText(_translate("detect", "STOP"))
